### ISSUE TITLE
react-native-geolocation在手机上定位正常，在pda上不能定位

### ISSUE THREAD

**Issue by weizhishu1901** [react-native-geolocation/react-native-geolocation#124]
1、安装在手机上正常 系统是Android9或者android10的
2、安装在pda上不能定位 系统是android 6
3、"@react-native-community/geolocation": "^2.0.2",
4、"react-native": "0.63.2",
5、权限设置如下
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

6、<---------------------------报错信息如下------------------->
            PERMISSION_DENIED: 1
            POSITION_UNAVAILABLE: 2
            TIMEOUT: 3
            code: 3
            message: "Location request timed out"

**Comment by raazatul7** [comment]
Same here!
It won't as to turn on the GPS.
When I turned in manually it says **Location request timed out**
