### ISSUE TITLE
@react-native-community/geolocation: NativeModule.RNCGeolocation is null

### ISSUE THREAD

**Issue by maulik-vekariya** [react-native-geolocation/react-native-geolocation#136]
## Ask your Question
  ERROR    Error: @react-native-community/geolocation: NativeModule.RNCGeolocation is null. To fix this issue try these steps:
• Run `react-native link @react-native-community/geolocation` in the project root.
• Rebuild and re-run the app.
• If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-geolocation
[Fri Jan 01 2021 15:08:07.695]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by esadkrs** [comment]
@maulik-vekariya  Did you find a solution?

**Comment by TopTalent333** [comment]
Hi, I had the same error.
Could you please give me solution?
thanks
