### ISSUE TITLE
Speed is always 0 for ANDROID

### ISSUE THREAD

**Issue by shoaib2527** [react-native-geolocation/react-native-geolocation#138]
I want to detect speed , I'm using watch position which returns "speed" along with other attributes. 
Its working fine in IOS, it returns valid speed. 
But for android its always zero. Weather device is travelling or not.
Am I missing anything?
Any help will be appreciated.
Thanks in advance.

**Comment by DavidGonzalezGutierrez** [comment]
Yeah!
And the heading too.
Both for IOS and ANDROID.

**Comment by develotechnologies** [comment]
@DavidGonzalezGutierrez  I'll try it today.
I have already managed first slow position by calling getcurrentposition before watch position.
I'll update here after trying.
Thanks for the answer.

**Comment by shoaib2527** [comment]
@DavidGonzalezGutierrez  It Worked. Thanks

**Comment by shoaib2527** [comment]
Hi @0xtechie,
This piece of code works fine.

       const subscirbeTooLocation = () => {

        window.locationListenerId = RNLocation.subscribeToLocationUpdates(

          (position) => {

            dispatch(

              setLocation({

                location: [position[0].longitude, position[0].latitude],

                speed: position[0].speed,

              }),

            );

          },

        );

      };
  
  Note: I switched to 'react-native-location' due to some other reason.

**Comment by fukemy** [comment]
hi @shoaib2527, can u confirm which is better? I want to calculating speed based on location. So I need more effection speed caluclating
